#!/usr/bin/env bash
#
# options=" Lock\n Suspend\n Logout\n Reboot\n Shutdown"
options=" \n \n \n \n "

chosen=$(echo -e "$options" | rofi -dmenu -i -p "Power" -theme ~/.config/rofi/powermenu2.rasi)

case "$chosen" in
" ") ~/.config/i3/scripts/blur-lock ;;
" ") systemctl suspend ;;
" ") i3-msg exit ;;
" ") systemctl reboot ;;
" ") systemctl poweroff ;;
esac
