os:
  # Command for editing a file. Should contain "{{filename}}".
  edit: "nvim {{filename}}"
  
  # Command for editing a file at a given line number. Should contain
  # "{{filename}}", and may optionally contain "{{line}}".
  editAtLine: "nvim +{{line}} {{filename}} "
