backend = "glx";
vsync = true;
# Opacity
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;

# corner radius
#corner-radius = 7;

# shadows
shadow = false;

opacity-rule = [
# transparency with tabbed/stacked window
    "0:_NET_WM_STATE@[*]:a = '_NET_WM_STATE_HIDDEN'",
    "80:class_g = 'i3bar'"
];

#Parameters for the blur effect
blur: {
  method = "dual_kawase";
  strength = 7;
  background = true;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "class_g = 'kitty'"
];
