backend = "glx";
vsync = true;

#################################
#             Opacity           #
#################################

# Enable opacity but dont make everything transparent
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;

opacity-rule = [
# transparency with tabbed/stacked window
    "0:_NET_WM_STATE@[*] = '_NET_WM_STATE_HIDDEN'",
    "50:class_g = 'i3bar'"
];

#################################
#             Blur           #
#################################
#
#Parameters for the blur effect
blur: {
  method = "dual_kawase";
  strength = 7;
  background = true;
  background-frame = false;
  background-fixed = false;
}

# Who doesnt like transparent terminal
blur-background-exclude = [
  "class_g = 'kitty'",
  "class_g = 'Peek'",
  "_NET_WM_STATE@[*] = '_NET_WM_STATE_HIDDEN'",
  "class_g = 'zen' && window_type = 'popup_menu'",
  "class_g = 'zen' && window_type = 'utility'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#             Shadows           #
#################################

shadow = true;

# The blur radius for shadows, in pixels. (defaults to 12)
shadow-radius = 30;

# The opacity of shadows. (0.0 - 1.0, defaults to 0.75)
shadow-opacity = 0.50

#shadow-opacity = 0.8;
#shadow-offset-x = 4;
#shadow-offset-y = 4;

shadow-exclude = [
  "class_g = 'flameshot'",
  "class_g = 'zen' && window_type = 'popup_menu'",
  "class_g = 'zen' && window_type = 'utility'",
  "_GTK_FRAME_EXTENTS@:c"
];

focus-exclude = [
  "class_g = 'flameshot'",
];

#################################
#     Animation Settings    #
#################################
animations = (
{
    triggers = ["close"];
    opacity = {
      curve = "cubic-bezier(0,1,1,1)";
      duration = 0.1;
      start = "window-raw-opacity-before";
      end = 0;
    };
    blur-opacity = "opacity";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-y = {
      curve = "cubic-bezier(0,1.3,1,1)";
      duration = 0.2;
      start = 1;
      end = 0.6;
    };
    scale-x = 1;
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },

  {
    triggers = ["open"];
    opacity = {
      curve = "linear";
      duration = 0.05;
      start = 0;
      end = "window-raw-opacity";
    };
    blur-opacity = "opacity";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-y = {
      curve = "cubic-bezier(0,1.3,1,1)";
      duration = 0.3;
      start = 0.6;
      end = 1;
    };
    scale-x = 1;
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },

  {
    triggers = ["show"];
    opacity = {
      curve = "linear";
      duration = 0.1;
      start = 0;
      end = "window-raw-opacity";
    };
  },
   {
   triggers = ["hide"];
   opacity = {
     curve = "linear";
     duration = 0.2;
     start = "window-raw-opacity-before";
     end = 0;
   };
   blur-opacity = "opacity";
   shadow-opacity = "opacity";
 },

  {
    triggers = ["geometry"]
    scale-x = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.22;
      start = "window-width-before / window-width";
      end = 1;
    }
    scale-y = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.22;
      start = "window-height-before / window-height";
      end = 1;
    }
    offset-x = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.22;
      start = "window-x-before - window-x";
      end = 0;
    }
    offset-y = {
      curve = "cubic-bezier(0,0,0,1.28)";
      duration = 0.22;
      start = "window-y-before - window-y";
      end = 0;
    }

    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  }
)
